### ISSUE TITLE
Change setup to only require api key

### ISSUE THREAD

**Issue by smulle48** [fars-fede-fire/clever_api#11]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

It it possible to change the setup, so you only have to enter your api key ?

### Describe alternatives you've considered

-

### Additional context

I've already got access to my api key and can call everything from curl so if the setup could be change to only require input of the api key :-)

**Comment by fars-fede-fire** [comment]
No. 
That would still require the URLs to be exposed from within the component. 
Alternatively you can create your own sensor from Home Assistant using a REST sensor.

**Comment by smulle48** [comment]
Nevermind. Got it working on my own :-)
