### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by nagydavid** [fars-fede-fire/clever_api#12]
## System Information

version | core-2023.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.32.1
Stage | running
Available Repositories | 1293
Downloaded Repositories | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 62.3 GB
disk_used | 38.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (15.0.8), Cloudflared (4.2.7), ESPHome (2023.8.3), Home Assistant Google Drive Backup (0.111.1), Mosquitto broker (6.3.1), PS5 MQTT (1.3.1), Piper (1.3.2), Portainer (2.0.0), Samba share (10.0.2), Studio Code Server (5.10.2), Vaultwarden (Bitwarden) (0.20.0), MariaDB (2.6.1), go2rtc (1.7.1), Node-RED (14.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 32
views | 1
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 15, 2023 at 19:24
-- | --
current_recorder_run | September 23, 2023 at 17:17
estimated_db_size | 6159.80 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I am getting internal server error when I am trying to initialise the integration. Is it  the result of the API deprecation or removal?

### Reproduction steps

- Intstalled trough HACS.

### Debug logs

```text
No logs can be given. Integration cannot be initialised.
```

**Comment by nagydavid** [comment]
I know there was a deprecation of APIs, but I saw some activity in the repo, so I assumed there is some work around.

**Comment by smulle48** [comment]
> I know there was a deprecation of APIs, but I saw some activity in the repo, so I assumed there is some work around.

I've made a PR waiting for it to be accepted (should be fixed now) :-D . That will fix that error.

**Comment by fars-fede-fire** [comment]
The updates are for making it more generic and easier to use it as template for other integrations. 
If you want to use the integration for Clever you have to obtain the URLs yourself for example using mitmproxy.

**Comment by nagydavid** [comment]
Lets, say I have the URLs, I am having and unknown  error after the email added to the integration initialization, eventhough the URL works through postman

**Comment by nagydavid** [comment]
never mind.

**Comment by nagydavid** [comment]
@smulle48 @fars-fede-fire  Sorry people last quetion. I cannot find any reference for the endpoint of VERIFY_LINK_CUTOFF.
By the way thanks for pointing me to the mitmproxy, it's a cool stuff. :)

**Comment by smulle48** [comment]
> @smulle48 @fars-fede-fire  Sorry people last quetion. I cannot find any reference for the endpoint of VERIFY_LINK_CUTOFF.
> 
> By the way thanks for pointing me to the mitmproxy, it's a cool stuff. :)

The email you get. That url actually contains two url.

The cutoff ends just before the second https in that url.

It could probably be done more elegant, but it do the job :-)

**Comment by nagydavid** [comment]
@fars-fede-fire @smulle48 , Did they just killed the add-on by changing the verification email?

**Comment by smulle48** [comment]
> @fars-fede-fire @smulle48 , Did they just killed the add-on by changing the verification email?
> 
> 

You can try this, to see if that works better

https://github.com/smulle48/clever_api

**Comment by nagydavid** [comment]
I am getting the same error:
![image](https://github.com/fars-fede-fire/clever_api/assets/10994218/5d93fb76-2600-4f4b-9383-1adb34acc80d)

**Comment by smulle48** [comment]
> I am getting the same error:
> 
> ![image](https://github.com/fars-fede-fire/clever_api/assets/10994218/5d93fb76-2600-4f4b-9383-1adb34acc80d)
> 
> 
> 
> 

I don't know if it was a bug at Clever's end, but it's working again here

**Comment by fars-fede-fire** [comment]
Currently I am working on a integration for my Volvo EV, so the Clever API integration is right now a lower priority although I have some ideas for optimazition.
