### ISSUE TITLE
can send authorization email

### ISSUE THREAD

**Issue by runeniels** [fars-fede-fire/clever_api#15]
### System Health details

none

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

when i have to write my mail, it somes with an error 
![image](https://github.com/fars-fede-fire/clever_api/assets/152495279/a6d0a9bc-30b3-4fb9-9542-4d03cfa145d8)

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
i am new to github
```

### Diagnostics dump

i am new to github

**Comment by fars-fede-fire** [comment]
Clever has asked not to get their api endpoints shared. 
See the readme. 
If you want to use this integration you have to find and insert the endpoints yourself.
